# Generated by Django 4.0.4 on 2022-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_game_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(0, 'Hidden'), (1, 'Visible')], default=1),
        ),
    ]
