name: Auto Deploy to render.com
on:
  push:
    branches:
      - $default-branch

jobs:
  auto_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering deploy hook on render.com"
      - run: curl --request POST "${{ secrets.RENDER_SECRET_DEPLOY_URL }}"
