name: Auto Deploy to render.com
on:
  push:
    branches: [ main ]

jobs:
  auto_deploy:
    name: Webhook deploy to render.com
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering deploy hook on render.com"
      - run: curl --request POST "${{ secrets.RENDER_SECRET_DEPLOY_URL }}"
